Add initial draft and link in README
cisagov/action-lineage pull request #13
Opened 2020-09-04 17:28 UTC by hillaryj

Adds a draft of documentation on how to skeletonize / add Lineage to a repository.

## 🗣 Description

The initial sections have been tested out, there's a note on where the instructions need additional fleshing-out.

Also adds a line into the main README.

## 💭 Motivation and Context

## 🧪 Testing

Pre-commit hooks passed.

## 📷 Screenshots (if appropriate)

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-09-08 14:00 UTC, jsf9k requested changes
I have some suggestions for improvement.  In particular, I think this document covers a lot more than just adding Lineage to an existing repo; hence, I think it would be better if it lived in [cisagov/development-guide](https://github.com/cisagov/development-guide).

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +1. In the target repo, add the skeleton as a remote
I would go ahead and mention the full `git` commands for this step and the next one.

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +4. Fix problems that may arise from `pre-commit` being added
You should probably add a step before this that mentions running `pre-commit install`.

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +# After fixing them, add each file and then commit to complete the merge
I would make this comment more explicit, so folks don't add a single file and then commit.  Something like, "After fixing the merge conflicts in a file, `git add` it.  When all conflicts have been fixed and added, `git commit` to complete the merge."

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +git commit --message="Merge skeleton history"
Can't we just use the default commit message here that `git` produces for the merge commit?  That message mentions the branches being merged from and to, so it is slightly more informative.

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +# Adding Lineage to a non-skeletonized repository #
These instructions cover a lot more than just adding Lineage.  They describe how to add a skeleton to an existing repository.  I suggest changing the title and the file name accordingly.

Also, [cisagov/development-guide](https://github.com/cisagov/development-guide) may be a better home for this document.

2020-09-08 14:00 UTC, jsf9k commented on Add-Lineage.md
> +  - Once the commit/repo is up, add a token from
Not all repositories need this.

2020-10-28 13:59 UTC, hillaryj commented
I'm closing this PR in favor of moving the documentation to `development-guide` as suggested. I've incorporated the feedback given here - thanks!

2020-10-28 13:59 UTC, closed without merging